export const types = {
  USUARIO_AUTENTICADO: "USUARIO_AUTENTICADO",
  REGISTRO_EXISTOSO: "REGISTRO_EXISTOSO",

  REGISTRO_ERROR: "REGISTRO_ERROR",

  MOSTRAR_MENSAJE: "MOSTRAR_MENSAJE",
  LIMPIAR_MENSAJE: "LIMPIAR_MENSAJE",

  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_EXITO: "LOGIN_EXITO",

  CERRAR_SESION: "CERRAR_SESION",

  CARGANDO: "CARGANDO",
  SUBIR_ARCHIVO_EXITO: "SUBIR_ARCHIVO_EXITO",
  SUBIR_ARCHIVO_ERROR: "SUBIR_ARCHIVO_ERROR",

  CREAR_ENLACE_EXITO: "CREAR_ENLACE_EXITO",
  CREAR_ENLACE_ERROR: "CREAR_ENLACE_ERROR",
};
