export const types = {
  USUARIO_AUTENTICADO: "USUARIO_AUTENTICADO",
  REGISTRO_EXISTOSO: "REGISTRO_EXISTOSO",

  REGISTRO_ERROR: "REGISTRO_ERROR",
  LIMPIAR_MENSAJE: "LIMPIAR_MENSAJE",

  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_EXITO: "LOGIN_EXITO",

  CERRAR_SESION: "CERRAR_SESION",
};
